/* Run inside a browser with the game loaded. Assertions use real simulation paths. */
(() => {
 const A=SVG_FIGHTER,G=A.state,results=[];
 const test=(name,fn)=>{try{const info=fn();results.push({name,pass:true,...(info||{})});}catch(e){results.push({name,pass:false,error:e.message,stack:e.stack});}};
 const ok=(v,msg)=>{if(!v)throw Error(msg||'assertion failed');};
 function setup(id='mai',facing=1){A.start(id,'ryu','training','classic');G.phase='fight';G.paused=false;document.getElementById('dummy').value='idle';document.getElementById('infinite').checked=false;document.getElementById('autohp').checked=false;const [f,d]=A.fighters;f.x=f.px=facing===1?330:1110;d.x=d.px=facing===1?1110:330;f.dir=facing;d.dir=-facing;return [f,d];}
 const tick=n=>A.step(n);
 function direction(n,face){const xy={1:[-1,1],2:[0,1],3:[1,1],4:[-1,0],5:[0,0],6:[1,0],7:[-1,-1],8:[0,-1],9:[1,-1]}[n],next=new Set();if(xy[0])next.add(xy[0]*face>0?'right':'left');if(xy[1])next.add(xy[1]>0?'down':'up');for(const b of ['left','right','up','down'])if(!next.has(b))A.release(0,b);for(const b of next)A.press(0,b);}
 function command(pattern,button,face=1,hold=false){for(const n of pattern){direction(+n,face);tick(2);}A.press(0,button);tick(3);if(!hold)A.release(0,button);return A.fighters[0].attack?.m.id;}
 const expected=[['236','LP','kachosen_0'],['214','MP','hissatsu_1'],['623','MK','ryuenbu_1'],['236','HK','shinobibachi_2'],['236236','LP','SA1'],['236236','LK','SA2'],['214214','LP','SA3']];
 for(const face of [1,-1])for(const [pat,b,id]of expected)test(`Mai ${face>0?'right':'left'} ${pat}+${b} → ${id}`,()=>{setup('mai',face);const got=command(pat,b,face);ok(got===id,`expected ${id}, got ${got}`);});
 for(const face of [1,-1])test(`Mai air 214P / ${face}`,()=>{const[f]=setup('mai',face);f.y=f.py=-210;f.vy=-2;ok(command('214','LP',face)==='musabi_0','air command did not select Musasabi');});
 for(const face of [1,-1])test(`Mai air SA2 / ${face}`,()=>{const[f]=setup('mai',face);f.y=f.py=-210;f.vy=-3;ok(command('236236','LK',face)==='SA2','air SA2 failed');});
 test('Mai ground-only SA1 / SA3 cannot start in air',()=>{const[f]=setup();f.y=-100;ok(!A.move(0,'SA1'));ok(!A.move(0,'SA3'));ok(f.super===3);});
 test('SA1 creates exactly five flame stocks at activation',()=>{const[f]=setup();ok(A.move(0,'SA1'));ok(f.flameStock===0);tick(31);ok(f.flameStock===5,`stock=${f.flameStock}`);ok(f.super===2);});
 test('Accepted special spends one stock, rejected input does not',()=>{const[f]=setup();f.flameStock=5;ok(A.move(0,'hissatsu_0'));ok(f.flameStock===4);ok(f.attack.m.flameEnhanced);ok(!A.move(0,'ryuenbu_0'));ok(f.flameStock===4);});
 test('SA3 does not consume flame stock',()=>{const[f]=setup();f.flameStock=5;ok(A.move(0,'SA3'));ok(f.flameStock===5);});
 test('Round reset clears flame stock and follow window',()=>{const[f]=setup();f.flameStock=5;f.maiFollowUntil=G.tick+99;A.reset();ok(f.flameStock===0&&f.maiFollowUntil===0);});
 test('Uncharged fan has one hit, is strike-vulnerable',()=>{setup();A.move(0,'kachosen_0');tick(16);const s=G.shots.find(s=>s.owner.index===0);ok(s,'fan missing');ok(s.hits===1&&s.vulnerable&&!s.fanCharged);});
 test('Hold P creates a protected fan with physical bounce',()=>{const[f,d]=setup();d.x=740;ok(command('236','LP',1,true)==='kachosen_0');tick(40);A.release(0,'LP');const s=G.shots.find(s=>s.owner===f);ok(s,'charged fan missing');ok(s.fanCharged&&!s.vulnerable&&s.hits>=1,JSON.stringify({charged:s.fanCharged,vulnerable:s.vulnerable,hits:s.hits,phase:s.fanPhase,x:s.x,y:s.y,at:f.attack?.t}));let bounce=false,fall=false,firstY=0;for(let i=0;i<130;i++){tick(1);if(s.fanPhase==='rising'){bounce=true;firstY=s.y;ok(s.lockedTarget==null,'charged fan must not lock onto target');}if(s.fanPhase==='falling')fall=true;if(s.life<=0)break;}ok(bounce&&fall,`bounce=${bounce},fall=${fall},phase=${s.fanPhase}`);ok(d.hp<10000);return{damage:10000-d.hp};});
 test('Normal fan loses to an opposing Hadoken without deleting it',()=>{const[f,d]=setup();f.x=420;d.x=980;A.move(0,'kachosen_0');A.move(1,'hadoken_0');tick(19);const fan=G.shots.find(s=>s.owner===f),wave=G.shots.find(s=>s.owner===d);ok(fan&&wave,'both projectiles must spawn');for(let i=0;i<80&&fan.life>0;i++)tick(1);ok(fan.life<=0);ok(wave.life>0,`Hadoken life=${wave.life}`);});
 test('OD charged fan allows forward+P follow-up and two separate fans',()=>{const[f,d]=setup();d.x=1300;f.x=200;ok(command('236','PP',1,true)==='kachosen_3');tick(35);A.release(0,'PP');ok(f.maiFollowUntil>G.tick,'follow window missing');const before=G.shots.length;direction(6,1);A.press(0,'HP');tick(3);A.release(0,'HP');ok(f.attack?.m.id==='midare',`got ${f.attack?.m.id}`);tick(17);ok(G.shots.length>=before+2,`shots=${G.shots.length},before=${before}`);ok(f.drive<4.1&&f.drive>=4);});
 test('Standalone midare cannot bypass prerequisites',()=>{setup();ok(!A.move(0,'midare'));});
 test('OD Shinobi Bachi hit rebounds into an actionable airborne state',()=>{const[f,d]=setup();f.x=480;d.x=710;A.move(0,'shinobibachi_3');let bounced=false;for(let i=0;i<100;i++){tick(1);if(f.maiAirFollow>G.tick){bounced=true;break;}}ok(bounced,'no OD hit rebound');ok(f.y<0&&!f.airLock&&!f.attack);ok(A.move(0,'musabi_0'),'air follow-up rejected');});
 test('Mai SA2 ignores projectile contact during its active travel',()=>{const[f,d]=setup();A.move(0,'SA2');G.hitstop=0;f.attack.t=f.attack.m.startup+2;f.invuln=0;const hp=f.hp;const res=A.contact(d,f,A.getMove(d,'hadoken_0'),0,true);ok(res==='immune'&&f.hp===hp);});
 test('Mai pillar has a bilateral, vertical hitbox; DP uses a foot',()=>{const[f]=setup();A.move(0,'SA1');f.attack.t=f.attack.m.startup;const g=A.geometry(f);ok(g.hit.some(b=>b.part==='flame-pillar'&&b.h>250&&b.x<f.x));A.setState(f,'idle');f.invuln=0;A.move(0,'ryuenbu_0');f.attack.t=f.attack.m.startup;const h=A.geometry(f);ok(h.hit.some(b=>b.part==='foot'));ok(!h.hit.some(b=>b.part==='fan'));});
 for(const id of ['ryu','ken','chun','cammy','luke','juri','mai','iori'])test(`${id} drive meter / burnout / super cost`,()=>{const[f]=setup(id);A.move(0,'DI');ok(f.drive===5);A.setState(f,'idle');f.drive=.3;ok(!A.move(0,'DI'));ok(f.drive===.3);f.drive=0;f.burnout=true;const od=A.moves[id].find(m=>m.od);ok(!A.move(0,od.id));f.burnout=false;f.drive=6;A.move(0,'SA3');ok(f.super===0);});
 G.paused=true;return results;
})();
